# اسم الملف: .github/workflows/snake.yml

name: Generate snake animation

on:
  schedule:
    # سيتم التشغيل كل 12 ساعة في تمام الساعة (وليس كل دقيقة)
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg for both light and dark themes
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          
          # هذا هو الجزء الأهم: إنشاء ملفين مختلفين
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark&color_snake=cyan
            
      - name: Push generated files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
